package com.cloud2bubble.ptsense;

import java.util.HashMap;
import java.util.Map;

public class PTService {

	public static Map<String, Map<String, String[]>> SERVICES = new HashMap<String, Map<String, String[]>>();

	static {
		Map<String, String[]> STOPS_MPORTO = new HashMap<String, String[]>();
		STOPS_MPORTO.put("A", new String[] { "Estádio do Dragão", "Campanhã",
				"Heroísmo", "Campo 24 de Agosto", "Bolhão", "Trindade", "Lapa",
				"Carolina Michaelis", "Casa da Música", "Francos", "Ramalde",
				"Viso", "Sete Bicas", "Senhora da Hora", "Vasco da Gama",
				"Estádio do Mar", "Pedro Hispano", "Parque Real",
				"Câmara de Matosinhos", "Matosinhos Sul", "Brito Capelo",
				"Mercado", "Senhor de Matosinhos" });

		STOPS_MPORTO.put("B",
				new String[] { "Estádio do Dragão", "Campanhã", "Heroísmo",
						"Campo 24 de Agosto", "Bolhão", "Trindade", "Lapa",
						"Carolina Michaelis", "Casa da Música", "Francos",
						"Ramalde", "Viso", "Sete Bicas", "Senhora da Hora",
						"Fonte do Cuco", "Custóias", "Esposade", "Crestins",
						"Verdes", "Pedras Rubras", "Lidador",
						"Vilar do Pinheiro", "Modivas Sul", "Modivas Centro",
						"Mindelo", "Espaço Natureza", "Varziela", "Árvore",
						"Azurara", "Santa Clara", "Vila do Conde",
						"Alto do Pega", "Portas Fronhas", "São Brás",
						"Póvoa de Varzim" });

		STOPS_MPORTO.put("C", new String[] { "Campanhã", "Heroísmo",
				"Campo 24 de Agosto", "Bolhão", "Trindade", "Lapa",
				"Carolina Michaelis", "Casa da Música", "Francos", "Ramalde",
				"Viso", "Sete Bicas", "Senhora da Hora", "Fonte do Cuco",
				"Cândido dos Reis", "Pias", "Araujo", "Custió",
				"Parque da Maia", "Fórum da Maia", "Zona Industrial", "Mandim",
				"Castêlo da Maia", "ISMAI" });

		STOPS_MPORTO.put("D", new String[] { "Hospital de São João", "IPO",
				"Pólo Universitário", "Salgueiros", "Combatentes", "Marquês",
				"Faria Guimarães", "Trindade", "Aliados", "São Bento",
				"Jardim do Morro", "General Torres", "Câmara Gaia",
				"João de Deus", "D. João II", "Santo Ovídio" });

		STOPS_MPORTO.put("E", new String[] { "Estádio do Dragão", "Campanhã",
				"Heroísmo", "Campo 24 de Agosto", "Bolhão", "Trindade", "Lapa",
				"Carolina Michaelis", "Casa da Música", "Francos", "Ramalde",
				"Viso", "Sete Bicas", "Senhora da Hora", "Fonte do Cuco",
				"Custóias", "Esposade", "Crestins", "Verdes", "Botica",
				"Aeroporto" });

		STOPS_MPORTO
				.put("F", new String[] { "Fânzeres", "Venda Nova", "Carreira",
						"Baguim", "Campainha", "Rio Tinto", "Levada",
						"Nau Vitória", "Nasoni", "Contumil",
						"Estádio do Dragão", "Campanhã", "Heroísmo",
						"Campo 24 de Agosto", "Bolhão", "Trindade", "Lapa",
						"Carolina Michaelis", "Casa da Música", "Francos",
						"Ramalde", "Viso", "Sete Bicas", "Senhora da Hora" });

		Map<String, String[]> STOPS_STCP = new HashMap<String, String[]>();
		STOPS_STCP.put("1", new String[] { "Infante", "Alfândega",
				"Museu Vinho Porto", "Museu C. Eléctrico", "Bicalho",
				"Ponte Arrábida", "Sécil", "Gás", "Fluvial", "D.leonor",
				"Cantareira", "Passeio Alegre" });

		STOPS_STCP.put("10", new String[] { "Lameira", "Escola Primária",
				"R. Capela", "Belói", "Mó", "Terra Nova", "Carvalheiras",
				"Félix", "Camões", "Dr. Pedro Vitorino", "Escola Preparatoria",
				"Rio Ferreira", "Covilhã", "Fonte Telha", "Rosa Damasceno",
				"Farmacia", "1 Maio", "Vila Verde", "Ervedosa" });

		STOPS_STCP.put("18", new String[] { "Museu C. Eléctrico",
				"Entre Quintas", "Restauração", "Viriato", "Carmo" });

		STOPS_STCP.put("22", new String[] { "Carmo", "Clérigos",
				"Pr. Da Liberdade", "Batalha", "Batalha-guindais",
				"Santa Catarina", "Pr. D. João I", "Av. Aliados",
				"Pr. Filipa De Lencastre", "Guilherme Gomes Fernandes" });

		STOPS_STCP.put("55", new String[] { "Bolhão-mercado", "Sta. Catarina",
				"Largo Do Padrão", "Campo 24 De Agosto", "Nave", "Barros Lima",
				"Pr. Das Flores", "Av. 25 De Abril", "Fonte Velha",
				"Estádio Do Dragão", "Corujeira", "Ferr. Dos Santos", "Falcão",
				"Cartes", "Escolas", "S. Roque", "Tv. Da Ponte", "S. Caetano",
				"David Correia Silva", "D.sancho I", "Cruzeiro",
				"Igreja Rio Tinto 1", "Lourinha", "Perlinhas",
				"Rio Tinto (estação)", "Joaquim Neves", "Campainha",
				"Novo Cemitério", "Paço", "Quinta Do Paço", "Baguim",
				"Baguim (igreja)", "Escola Frei Manuel", "Sta. Inês",
				"Miguel Torga", "Quinta Da Missilva", "Missilva (piscinas)" });

		STOPS_STCP.put("61", new String[] { "Matosinhos Mercado", "S. Pedro",
				"Lota", "Godinho", "Matosinhos Praia", "Afonso Cordeiro",
				"Afonso Henriques", "Matosinhos (CMM)", "Goa",
				"Hospital Matosinhos", "Seara", "Sendim (cemitério)",
				"Sarilho", "R.lagoa", "C. Saude Da Sra. Hora", "C. C. Londres",
				"Quatro Caminhos", "R. Nova S. Gens", "António Pedro",
				"Sta. Apolonia", "Fogueteiros", "Padrão Légua",
				"Central Seixo", "Via Norte", "Picoutos", "Picoutos (viaduto)",
				"Pedra Verde", "Godinho Faria", "S. Mamede", "Laranjeiras",
				"Tv. Henrique Bravo", "Leonardo Coimbra", "Parada",
				"Rod. Gonçalves Lage (este)", "Gago Coutinho", "Formigueiro",
				"António Santos", "R. Do Mosteiro", "Águas Santas", "Corga",
				"Lavadouros", "Alto Da Maia", "Av.lidador Da Maia",
				"Palmilheira", "Heróis De Angola", "Padre Américo", "Formiga",
				"Duarte Pacheco", "4 Caminhos", "Tapada Azevedo",
				"Flor Da Serra", "Alto Da Serra", "Ribeiro Cambado",
				"Fonte Da Senhora", "Gaspar Corte Real", "Vale Chãs",
				"25 De Abril", "Pav. Gimnodesport.", "Calvário",
				"Câmara De Valongo", "Valongo (centro)", "Padrão", "Presa",
				"Aguiar Nogueira", "Valongo (estação)" });

		STOPS_STCP.put("64",
				new String[] { "Valongo", "5 Outubro", "Calvário",
						"Pav. Gimnodesport.", "Lagueirões", "Fonte", "Lousas",
						"Gandra Paciência", "Calfaiona", "António Sérgio",
						"Quinta Lousa", "Estação Serviço", "31 Janeiro",
						"Cabêda", "Viela S.vicente", "Oliveiras",
						"Aldeia Nova", "Barreira", "Igreja De Alfena",
						"Tv. Da Costa", "Alfena", "Alex. Herculano",
						"Codiceira", "Ferraria", "Ribeiro (alfena)" });

		STOPS_STCP.put("68", new String[] { "Hosp. S. João (metro)", "Asprela",
				"Enxurreiras", "Areosa (mercado)", "Areosa (feira)", "Triana",
				"Giesta", "Crespo", "Forno", "Tv. Brás Oleiro", "Tv. Forno",
				"Santegãos", "Forças Armadas", "Padre Ivo Tonelli", "Sra.lapa",
				"Boafé", "R. Casal", "R. Nova Sistelo", "Tv.castanheira",
				"Sistelo", "Bazar", "Rio Tinto (estação)", "Joaquim Neves",
				"Campainha", "Novo Cemitério", "Paço", "Quinta Do Paço",
				"Baguim", "Estrela", "Campinho", "Vale Ferreiros", "Pontelhas",
				"Carreira", "Ferraria", "Venda Nova", "Noé", "Felga",
				"Outeiro", "Lavadouros", "Montezelo", "Fanzeres (igreja)",
				"Costa", "Agras", "Álvarinho", "Sta. Cruz", "Sta. Eulália",
				"Capitão Moura", "Vilar", "Taralhão", "Vinhal",
				"Igreja Capuchinhos", "25 De Abril", "Combatentes G. Guerra",
				"Gondomar (câmara)", "B. V. Gondomar", "Gondomar" });

		STOPS_STCP.put("69", new String[] { "Bolhão-mercado", "Sta. Catarina",
				"Largo Do Padrão", "Campo 24 De Agosto", "Bonfim", "Godim",
				"Pr. Das Flores", "Av. 25 De Abril", "Fonte Velha",
				"Estádio Do Dragão", "Corujeira", "Ferr. Dos Santos", "Falcão",
				"Cartes", "Escolas", "S. Roque", "Tv. Da Ponte", "S. Caetano",
				"Sr. Do Calvário", "Chão Verde", "Cavada Nova", "S. Sebastião",
				"Venda Nova", "Noé", "Felga", "Outeiro", "Lavadouros",
				"Montezelo", "Fanzeres (igreja)", "Costa", "Agras",
				"Álvarinho", "Sta. Cruz", "Sta. Eulália", "Estivada",
				"Barreiros", "Sta.barbara", "Fanzeres (escola)",
				"Tv.bela Vista", "Alto Barreiros", "Montalto", "Vieira Sá",
				"Calvário", "Vanzeleres", "Escola Paço", "Centro Saúde",
				"Tv. Felga", "Sista", "Escola Primária", "Alto Regadas",
				"Seixo" });

		STOPS_STCP.put("70", new String[] { "Bolhão-mercado", "Sta. Catarina",
				"Largo Do Padrão", "Campo 24 De Agosto", "Bonfim", "Godim",
				"Pr. Das Flores", "Av. 25 De Abril", "Fonte Velha",
				"Estádio Do Dragão", "Corujeira", "Ferr. Dos Santos", "Falcão",
				"Cartes", "Escolas", "S. Roque", "Tv. Da Ponte", "S. Caetano",
				"Sr. Do Calvário", "Chão Verde", "Cavada Nova", "S. Sebastião",
				"Venda Nova", "Ferraria", "Carreira", "Pontelhas",
				"Vale Ferreiros", "Campinho", "Estrela", "Baguim", "Crasto",
				"Portocarro", "Presa Cano", "Paraíso", "Adão E Eva",
				"Auto Estrada", "Seminário Bom Pastor", "Formiga",
				"Padre Américo", "Norton Matos", "Bom Pastor",
				"Alberto Taborda", "Cruzeiro", "Ermesinde",
				"Ermesinde (estação)" });

		STOPS_STCP.put("94", new String[] { "Bolhão-mercado", "Sta. Catarina",
				"Largo Do Padrão", "Campo 24 De Agosto", "Bonfim", "Godim",
				"Pr. Das Flores", "Av. 25 De Abril", "Fonte Velha",
				"Estádio Do Dragão", "Corujeira", "Ferr. Dos Santos", "Falcão",
				"Cartes", "Escolas", "S. Roque", "Tv. Da Ponte", "S. Caetano",
				"Sr. Do Calvário", "Chão Verde", "Cavada Nova", "S. Sebastião",
				"Venda Nova", "Ferraria", "Carreira", "Pontelhas",
				"Vale Ferreiros", "Entre Cancelas", "Regadas", "Seixo",
				"Agostinho A. Sousa", "Monte Pedro", "Estr. D. Miguel",
				"Alto Da Serra", "Ribeiro Cambado", "Fonte Da Senhora",
				"Gaspar Corte Real", "Vale Chãs", "25 De Abril",
				"Pav. Gimnodesport.", "Calvário", "Câmara De Valongo",
				"Valongo (centro)", "Padrão", "Presa", "Aguiar Nogueira",
				"Valongo (estação)", "Águas Ferreas", "Chã", "Padre Américo",
				"Ponte Seca", "Campo" });

		STOPS_STCP.put("200", new String[] { "Bolhão", "Mercado Do Bolhão",
				"Pr. D. João I", "Guil. G. Fernandes", "Carmo",
				"Hosp. Sto. António", "Palácio", "Pr. Da Galiza",
				"Junta Massarelos", "Planetário", "Casa Das Artes",
				"Jardim Botânico", "Lordelo", "Palmeiras", "Fluvial (norte)",
				"Paulo Da Gama", "Pasteleira", "Torres", "Padre Luis Cabral",
				"Univ. Católica", "Pr. Do Império", "Mercado Da Foz",
				"Pr. De Liège", "Igreja Carmelitas", "Crasto", "Molhe",
				"Funchal", "Pêro Da Covilhã", "Timor", "Castelo Do Queijo" });

		STOPS_STCP.put("201", new String[] { "Sá Da Bandeira", "Av. Aliados",
				"Guil. G. Fernandes", "Carmo", "Hosp. Sto. António", "Palácio",
				"Pr. Da Galiza", "Boavista - B. Sucesso",
				"Boavista-Casa Da Música", "Agramonte", "Guerra Junqueiro",
				"António Cardoso", "Bessa", "Foco", "Pinheiro Manso",
				"Gomes Da Costa", "Paulo Novais", "Fonte Da Moura",
				"Bairro Vilarinha", "Lidador", "Pereiró", "Ezequiel Campos",
				"Man. P. Azevedo 3", "Imtt", "Viso (metro)", "Viso" });

		STOPS_STCP.put("202", new String[] { "Lóios", "Av. Aliados",
				"Trindade", "Gonçalo Cristóvão", "Pr. Da República",
				"Figueiroa", "Carvalhosa", "Hospital Militar",
				"Boavista Brasília", "Boavista-Casa Da Música", "Graciosa",
				"Casa De Saúde Da Boavista", "Sidónio Pais", "Av. Do Bessa",
				"S.joão Bosco", "S. João De Brito", "Alberto Macedo",
				"Bairro Da Previdência", "Bairro Da Vilarinha",
				"Fonte Da Moura", "Av.da Boavista", "Liceu Garcia Orta",
				"R. Crasto", "Lgo.nevogilde", "Nevogilde", "Marechal Saldanha",
				"Funchal", "Pêro Da Covilhã", "Timor", "Castelo Do Queijo" });

		STOPS_STCP.put("203", new String[] { "Marquês", "Faria Guimarães",
				"Antero De Quental", "Piscina Constit.", "Sapador. Bombeiros",
				"Bcg", "Serpa Pinto", "Ramada Alta", "Cruz Vermelha",
				"Boavista-Casa Da Música", "Agramonte", "Guerra Junqueiro",
				"António Cardoso", "Bessa", "Foco", "Pinheiro Manso",
				"Gomes Costa 1", "Serralves", "Afonso Albuquerque",
				"Serralves (museu)", "João Barros", "Segurança Social",
				"Pr. Do Império", "Mercado Da Foz", "Pr. De Liège",
				"Igreja Carmelitas", "Crasto", "Molhe", "Funchal",
				"Pêro Da Covilhã", "Timor", "Castelo Do Queijo" });

		STOPS_STCP.put("204", new String[] { "Hosp. S. João (circunvalação)",
				"Hosp. S. João (urgência)", "Esc. Sup. Educação",
				"Faculdade De Engenharia", "Faculdade De Economia",
				"Manuel Laranjeira", "Outeiro", "Salgueiros", "Augusto Lessa",
				"Aval Cima", "Bento Júnior", "Covelo", "Campo Lindo",
				"Vale Formoso", "Silva Porto", "Bica Velha", "Natária",
				"Carvalhido", "Casa De Saúde Da Boavista", "Moreira Sá",
				"Casa Da Música (metro)", "Boavista-Casa Da Música",
				"Bom Sucesso", "Pr. Da Galiza", "Junta Massarelos",
				"Planetário", "Casa Das Artes", "Jardim Botânico", "Lordelo",
				"Palmeiras", "Fluvial (norte)", "Paulo Da Gama", "Pasteleira",
				"Torres", "Padre Luis Cabral", "Univ. Católica",
				"Pr. Do Império", "Mercado Da Foz", "Foz" });

		STOPS_STCP.put("205",
				new String[] { "Campanhã", "Noeda", "Edp", "Freixo", "Bonjóia",
						"Lagarteiro", "Br.cerco Porto", "Pego Negro",
						"Bernardim Ribeiro", "S. Roque", "Fábrica Do Cobre",
						"Vila Cova", "Parque Nascente", "Ranha", "Rebordãos",
						"Varziela", "Rot. Da Areosa", "Areosa", "Enxurreiras",
						"Asprela", "Hosp. S. João (circunvalação)",
						"IPO (circunval.)", "S. Tomé", "Amial", "Capuchinhos",
						"Via Norte (circ.)", "Mte Burgos (circ.)", "Congostas",
						"Br. Sto. Eugénio", "Quartel Militar", "Alto Do Viso",
						"Sra. Penha", "Ruela", "Rot. AEP", "Preciosa",
						"Azenha De Cima", "Lidador /hospital",
						"Quinta Ingleses", "Real", "Teatro Vilarinha",
						"Parque Da Cidade", "D.afonso Henriques",
						"D. Afonso Cordeiro", "Pr. Cid. Salvador",
						"Edif. Transparente", "Castelo Do Queijo" });

		STOPS_STCP.put("206", new String[] { "Campanhã", "Piscina Campanhã",
				"Bonfim", "Campo 24 De Agosto", "D. João Iv", "Rua Firmeza",
				"Moreira", "Escola Normal", "Sto. Isidro",
				"Esc. Aurélia Sousa", "Marquês", "Faria Guimarães",
				"Constituição", "Vale Formoso", "Silva Porto", "Bica Velha",
				"Natária", "Carvalhido", "Castelos", "Maria Lamas", "Prelada",
				"Urb. Prelada", "Ramalde Do Meio", "Julgado De Paz", "Viso",
				"Viso (metro)", "Jerónimo Azevedo", "Bairro Do Viso",
				"R. Do Senhor", "Alto Do Viso", "Quartel Militar", "Cotovias",
				"Br. Sto. Eugénio (escola)" });

		STOPS_STCP.put("207", new String[] { "Campanhã", "Pinto Bessa",
				"Capela Sra. Saúde", "Heroismo", "Prado Repouso", "S. Lázaro",
				"Duque Loulé", "Alex. Herculano", "Batalha", "Pr. D. João I",
				"Guil. G. Fernandes", "Carmo", "Hosp. Sto. António", "Palácio",
				"Pr. Da Galiza", "Junta Massarelos", "Planetário",
				"Casa Das Artes", "Jardim Botânico", "Lordelo", "Aleixo",
				"Sta. Catarina", "Fluvial", "Paulo Da Gama",
				"Pousada Juventude", "Pasteleira", "Campo Pasteleira",
				"Igreja N. Sra Da Ajuda", "Br. Da Pasteleira",
				"Serralves (museu)", "Afonso Albuquerque", "João Barros",
				"Segurança Social", "Pr. Do Império", "Mercado Da Foz" });

		STOPS_STCP.put("208", new String[] { "Sá Bandeira", "Av. Aliados",
				"Guil. G. Fernandes", "Carmo", "Hosp. Sto. António", "Palácio",
				"Pr. Da Galiza", "Boavista - B. Sucesso",
				"Boavista-Casa Da Música", "Graciosa",
				"Casa De Saúde Da Boavista", "Sidónio Pais", "Av. Do Bessa",
				"S. João Bosco", "S. João De Brito", "Igreja De Ramalde",
				"Casa De Ramalde", "Br. Ramalde", "C. Saúde Ramalde",
				"Br. Campinas", "Antunes Guimarães", "Lidador",
				"Br. Fonte Da Moura", "Pedra Verde", "Lidador-soeiro Mendes",
				"C.saúde De Aldoar", "Martim Freitas", "Vila Nova",
				"Alcaide Faria", "Aldoar Junta Freg." });

		STOPS_STCP.put("300", new String[] { "Esc. Sup. Educação",
				"Faculdade De Engenharia", "Faculdade De Economia",
				"Manuel Laranjeira", "Outeiro", "Salgueiros",
				"Vitorino Damasio", "Costa Cabral", "Silva Tapada",
				"Diogo Cão", "Igreja Das Antas", "Monte Aventino",
				"S. Crispim", "Esc. Soares Dos Reis", "Barros Lima", "Nave",
				"Campo 24 De Agosto", "D. João IV", "Bolhão (metro)",
				"Mercado Do Bolhão", "Pr. D. João I", "Av. Aliados",
				"Guilherme Gomes Fernandes", "Carmo", "Hosp. Sto. António",
				"Maternidade", "Torrinha", "Carvalhosa", "Carolina Michaelis",
				"Cruz Vermelha", "Quinta Amarela", "Av. França", "Carvalhido",
				"Cintura Interna", "Parque Da Prelada", "Laroze Rocha",
				"Sta. Luzia", "Br. Do Amial", "Miosótis", "Telheira",
				"Almeida Valente", "ISEP", "Ilha Brava", "S. Tomé",
				"IPO (circunval.)", "Hosp. S. João (urgência)" });

		STOPS_STCP.put("301", new String[] { "Hosp. S. João (circunvalação)",
				"IPO (circunval.)", "S. Tomé", "Ilha Brava", "I.S.E.P.",
				"Almeida Valente", "R. Telheira", "Miosótis", "Br. Do Amial",
				"Sta. Luzia", "Alberto Sampaio", "Parque Da Prelada",
				"Cintura Interna", "Hosp. Prelada", "Br. Carvalhido",
				"Br. Carvalhido", "Monsanto", "Bica Velha", "Serpa Pinto",
				"Quinta Amarela", "Cruz Vermelha", "Carolina Michaelis",
				"Igreja Cedofeita", "Cedofeita", "Faculdade Direito",
				"Maternidade", "Miguel Bombarda", "Hosp. Sto. António",
				"Cordoaria", "Lóios", "Pr. D. João I", "Sta. Catarina",
				"Largo Do Padrão", "Campo 24 De Agosto", "Bonfim",
				"Barros Lima", "Esc. Soares Dos Reis", "S. Crispim",
				"Monte Aventino", "Alameda Das Antas", "Diogo Cão",
				"Silva Tapada", "Vitorino Damasio", "Salgueiros", "Outeiro",
				"Manuel Laranjeira", "Faculdade De Economia",
				"Faculdade De Engenharia", "Esc. Sup. Educação" });

		STOPS_STCP.put("302", new String[] { "Campo 24 De Agosto",
				"Largo Do Padrão", "Coliseu Do Porto", "Pr. D. João I",
				"Guil. G. Fernandes", "Carmo", "Hosp. Sto. António", "Palácio",
				"Pr. Da Galiza", "Boavista - B. Sucesso", "Boavista Correios",
				"Cruz Vermelha", "Ramada Alta", "Marracuene", "Monte Cativo",
				"Clube Ténis Porto", "Antero De Quental", "Faria Guimarães",
				"Marquês", "R. Da Alegria", "Sto. Isidro", "Escola Normal",
				"Moreira", "R. Firmeza", "Moreda" });

		STOPS_STCP.put("303", new String[] { "Campo 24 Agosto", "D. João Iv",
				"Rua Firmeza", "Moreira", "Escola Normal", "Sto. Isidro",
				"Esc. Aurélia Sousa", "Marquês", "Faria Guimarães",
				"Antero De Quental", "Piscina Constit.", "Sapador. Bombeiros",
				"Bcg", "Serpa Pinto", "Ramada Alta", "Cruz Vermelha",
				"Boavista-Casa Da Música", "Boavista Cemitério",
				"Boavista - B. Sucesso", "Pr. Da Galiza", "Palácio",
				"Hosp. Sto. António", "Cordoaria", "Est. S. Bento",
				"Lgo. 1º Dezembro", "Batalha", "S. Lázaro", "Padrão" });

		STOPS_STCP.put("304", new String[] { "Trindade", "Av. Aliados",
				"Guilherme Gomes Fernandes", "Carmo", "Oliveiras",
				"Mártires Liberdade", "Pr. República", "Lapa",
				"Hosp. Sta. Maria", "Constituição", "Vale Formoso",
				"C. Saúde Paranhos", "Arca D Água", "Cintura Interna",
				"Carlos Amarante", "Br. Regado", "Capela Sra. Fátima",
				"Br. Do Amial", "Sta. Luzia", "Alberto Sampaio",
				"Br. Sta. Luzia" });

		STOPS_STCP.put("305", new String[] { "Cordoaria", "Pr. D. João I",
				"Sta. Catarina", "Largo Do Padrão", "Campo 24 De Agosto",
				"Nave", "Barros Lima", "Esc. Soares Dos Reis", "S. Crispim",
				"Monte Aventino", "Antas (L. Cidadão)", "R. Contumil",
				"Br. Costa Cabral", "Sta. Justa", "Rodrigues Semide",
				"Rot. Da Areosa", "Areosa", "Enxurreiras", "Asprela",
				"Hosp. S. João (circunvalação)", "IPO (circunval.)" });

		STOPS_STCP.put("400", new String[] { "Est. S. Bento",
				"Lgo. 1º Dezembro", "Batalha", "S. Lázaro", "Duque Terceira",
				"Prado Repouso", "Heroismo", "Capela Sra. Saúde",
				"Pinto Bessa", "Campanhã", "Noeda", "Edp", "Freixo",
				"Sra. Da Hora", "S. Pedro", "Meiral", "Viela Meiral",
				"Lagarteiro", "Azevedo" });

		STOPS_STCP.put("402", new String[] { "Boavista - B. Sucesso",
				"Boavista-Casa Da Música", "Graciosa", "Oliveira Monteiro",
				"Marracuene", "Monte Cativo", "Clube Ténis Porto",
				"Antero De Quental", "Faria Guimarães", "Marquês",
				"R. Da Alegria", "Coutinho Azevedo", "S. Crispim",
				"Monte Aventino", "Antas (L. Cidadão", "Fernão Magalhães",
				"Fonte De Contumil", "Br. Contumil", "Contumil (metro)",
				"Cartes", "Beata Mafalda", "Sra.campanhã", "Navas Tolosa",
				"S. Roque G. Barros" });

		STOPS_STCP.put("500", new String[] { "Lóios", "Est. S. Bento",
				"Mouzinho Silveira", "Merc. Ferr. Borges", "Ribeira (infante)",
				"Miragaia", "Alfândega", "Museu Vinho Porto",
				"Museu C. Eléctrico", "Bicalho", "Ponte Da Arrábida", "Sécil",
				"Gás", "Cordoaria Velha", "Fluvial", "D. Leonor", "Cantareira",
				"Igreja Da Foz", "Castelo Da Foz", "Senhora Da Luz",
				"Praia Dos Ingleses", "Praia Da Luz", "Praia De Gondarém",
				"Crasto", "Molhe", "Homem Do Leme", "Pêro Da Covilhã", "Timor",
				"Castelo Do Queijo", "Edif. Transparente", "Pr. Cid. Salvador",
				"Sousa Aroso", "Av. Menéres", "Matosinhos Praia", "Godinho",
				"Lota", "S. Pedro", "Matosinhos Mercado" });

		STOPS_STCP.put("501", new String[] { "Sá Bandeira", "Av. Aliados",
				"Guil. G. Fernandes", "Carmo", "Hosp. Sto. António", "Palácio",
				"Pr. Da Galiza", "Boavista - B. Sucesso",
				"Boavista-Casa Da Música", "Graciosa",
				"Casa De Saúde Da Boavista", "Sidónio Pais", "Av. Do Bessa",
				"S. João Bosco", "S. João De Brito", "Igreja De Ramalde",
				"C. Saúde Ramalde", "Br. Campinas", "Antunes Guimarães",
				"Br. Fonte Da Moura", "Revilão", "Lidador/M. Moniz",
				"Pedra Verde", "Igreja De Aldoar", "Prof.melo Adrião",
				"Aldoar Junta Freg.", "Vilarinha", "Bairro Da Biquinha",
				"António Carneiro", "E. Sec. G. Zarco", "D. Nuno A. Pereira",
				"Fonte Luminosa", "Afonso Cordeiro", "Brito Capelo",
				"Matosinhos Praia" });

		STOPS_STCP.put("502", new String[] { "Bolhão", "Bolhão (firmeza)",
				"Jornal De Notícias", "Pr. Da República", "Figueiroa",
				"Carvalhosa", "Hospital Militar", "Boavista Brasília",
				"Boavista-Casa Da Música", "Agramonte", "Guerra Junqueiro",
				"António Cardoso", "Bessa", "Foco", "Pinheiro Manso",
				"Gomes Da Costa", "Paulo Novais", "Fonte Da Moura",
				"Liceu Garcia Orta", "Parque Da Cidade", "Nevogilde", "Malaca",
				"Castelo Do Queijo", "Edif. Transparente", "Pr. Cid. Salvador",
				"Sousa Aroso", "Av. Menéres", "Matosinhos Praia", "Godinho",
				"Lota", "S. Pedro", "Matosinhos Mercado" });

		STOPS_STCP.put("503", new String[] { "Casa Da Música (metro)",
				"Boavista-Casa Da Música", "Agramonte", "Guerra Junqueiro",
				"António Cardoso", "Bessa", "Foco", "Pinheiro Manso",
				"S. João De Brito", "Igreja De Ramalde", "Casa De Ramalde",
				"Eng. Ferreira Dias", "Man. P. Azevedo 1", "Man. P. Azevedo 2",
				"Man. P. Azevedo 3", "Imtt", "Viso (metro)", "Viso (metro)",
				"Jerónimo Azevedo", "Sete Bicas", "Sra. Da Penha", "R.senhor",
				"Quatro Caminhos", "C. C. Londres", "C. Saúde Da Sra. Hora",
				"Av. Vasco Da Gama", "Rua Da Lagoa", "Fonte Do Cuco",
				"Tv. Passos Manuel", "Passos Manuel", "Guifőes", "Mundo Novo",
				"Monte Dos Pipos", "Reguinho D Água", "Regedoura", "Ribeiro",
				"Abelheira", "Lomba", "Ponte Carro", "Lomba (gatőes)",
				"R. Ferroviário", "R. Boa Hora", "R. Padre Porto Carrero",
				"Gatőes" });

		STOPS_STCP.put("504", new String[] { "Casa Da Música (metro)",
				"Boavista-Casa Da Música", "Agramonte", "Guerra Junqueiro",
				"António Patrício", "Casa Das Artes", "Jardim Botânico",
				"Lordelo", "Aleixo", "Sta. Catarina", "Fluvial",
				"Paulo Da Gama", "Pousada Juventude", "Pasteleira",
				"Campo Pasteleira", "Igreja N. Sra Da Ajuda",
				"Br. Da Pasteleira", "João R. Cabrilho", "Pinhais Da Foz",
				"Alfredo Keil", "Cristo Rei", "Liceu Garcia Orta",
				"Av. Da Boavista", "Fonte Da Moura", "Liceu Garcia Orta",
				"Parque Cidade", "Bairro Ant. Aroso", "Igreja De Aldoar",
				"Pedra Verde", "Lidador-soeiro Mendes",
				"Hosp. Magalhães Lemos", "Lidador/Hospital", "Preciosa",
				"Norteshopping" });

		STOPS_STCP.put("505", new String[] { "Hosp. S. João (circunvalação)",
				"IPO (circunval.)", "S. Tomé", "Amial", "Telheiro", "Flores",
				"S. Mamede (mercado)", "S. Mamede", "Sá E Melo", "Vilar",
				"Pedra Verde", "Moinhos", "Maínça", "Arroteia", "Queirãos",
				"Rua De Mosteiro", "Tv.melo Pereira", "Lgo. Da Capela",
				"Cristovão Cernache", "Cemitério", "Ezequiel Campos",
				"Gondivai (sul)", "Est Prisional De Custoias",
				"Dr Domingos Bontempo", "Custóias", "Custóias (feira)",
				"R. Gatőes", "Cândido Reis (metro)", "Custóias (metro)",
				"Monte Dos Pipos", "Av. Salgado Zenha", "Tv. Passos Manuel",
				"Passos Manuel", "Guifőes", "Tourais", "Sarilhos",
				"Monte Castelo", "Paus", "Linhares", "Regadio",
				"Sendim (cemitério)", "Seara", "Hospital Matosinhos", "Goa",
				"Alfredo Cunha", "Matosinhos (igreja)", "Sr. Matosinhos",
				"S.pedro", "Matosinhos Mercado" });

		STOPS_STCP.put("506", new String[] { "Hosp. S. João (metro)",
				"Ricardo Alves", "Feliciana", "Cavadas", "Iscap", "Dr. Barros",
				"Oliveira Gaio", "R. Centro", "Almirante Reis", "Laranjeiras",
				"S. Mamede", "Godinho Faria", "Pedra Verde",
				"Picoutos (viaduto)", "Picoutos", "Via Norte", "Central Seixo",
				"Padrão Légua", "Fogueteiros", "Sta. Apolonia",
				"António Pedro", "R. Nova S. Gens", "Quatro Caminhos",
				"Sra. Hora (metro)", "Sra. Hora", "Carriçal",
				"Parque J. G. Laranjo", "Sra. Hora (hiper)", "Azenha De Cima",
				"Hosp. P. Hispano", "Quinta Seca", "Parque De Real",
				"E. Sec. G. Zarco", "D. Nuno A. Pereira", "Carcavelos",
				"Matosinhos (CMM)", "Goa", "Alfredo Cunha", "Álvaro Castelőes",
				"Brito Capelo", "Godinho", "Lota", "S. Pedro",
				"Matosinhos Mercado" });

		STOPS_STCP.put("507", new String[] { "Cordoaria", "Carmo",
				"Hosp. Sto. António", "Palácio", "Pr. Da Galiza",
				"Boavista - B. Sucesso", "Boavista-Casa Da Música", "Graciosa",
				"Casa De Saúde Da Boavista", "Sidónio Pais",
				"Francos Z. Industr", "Rot. AEP", "Continente",
				"Azenha De Cima", "Hosp. P. Hispano", "Quinta Seca",
				"Parque De Real", "E. Sec. G. Zarco", "D. Nuno A. Pereira",
				"Carcavelos", "Matosinhos (CMM)", "Goa", "Pq Basílio Teles",
				"Godinho", "1º De Dezembro", "Matosinhos Mercado",
				"Senhor Matosinhos", "Regadio", "Leça F. Clube",
				"Francisco Maia", "Exponor", "Exponor", "Assoc. Emp. Portugal",
				"Cais 6", "Quinta De Santiago", "Ponte Movel", "Fonte Vila",
				"Fresca", "Apdl", "Fuzelhas", "Oliveira Lessa", "Dois Amigos",
				"Nogueira Pinto", "Igreja Leça", "Pero Covilhã", "Sol Poente",
				"Humberto Cruz", "Leça Palmeira" });

		STOPS_STCP.put("508", new String[] { "Boavista - B. Sucesso",
				"Boavista Correios", "Cruz Vermelha", "Quinta Amarela",
				"Av.frança", "Carvalhido", "Cintura Interna",
				"Parque Da Prelada", "Sra. Do Porto", "Monte Dos Burgos",
				"C. Seixo (sul)", "Fogueteiros (sul)", "C. Seixo (norte)",
				"Padrão Da Légua", "Fogueteiros", "Rui Gameiro", "Avilhó",
				"Tv.fonte Velha", "Custóias (feira)", "Custóias", "Cal",
				"Ponte Carraquinho", "António José Almeida", "Tv. Pias",
				"Gondivinho", "Esposade", "Tv. De Linhares",
				"Viaduto Do Metro", "Tv. Pinguela", "Monte S. Brás",
				"Br. Guardas", "Aldeia Baixo", "Casa Do Povo",
				"Sta. Cruz Bispo", "Ponte Carro", "Monte Avó", "Gatanhal",
				"Baldőes", "Tv.trás", "Farrapas", "R.oriental",
				"Justino Marques", "Freixieiro", "Joaquim Andrade", "Barão",
				"Joaquim Alves Silva", "Perafita", "Montedouro", "Aldeia Nova",
				"Cartódromo", "Cabo Mundo" });

		STOPS_STCP.put("600",
				new String[] { "Av. Aliados", "Trindade", "Gonçalo Cristóvão",
						"Pr. Da República", "Lapa", "Hosp. Sta. Maria",
						"Constituição", "Vale Formoso", "C. Saúde Paranhos",
						"Arca D Água", "Cintura Interna", "Carlos Amarante",
						"Telheira", "Berlengas", "Amial", "Telheiro", "Flores",
						"S. Mamede (mercado)", "S. Mamede", "Sá E Melo",
						"C. Saúde S. Mamede", "Abel Salazar", "Ponte Da Pedra",
						"Pedro Mesquita", "Camilo C. Branco", "Santana",
						"Sra. Da Saúde", "Antonio Aleixo", "Catassol",
						"Combonianos", "Rot.lavrador", "Santos Leite",
						"Igreja Da Maia", "Maia (câmara)", "Fórum",
						"Ferreira Da Cruz", "Altino Coelho", "Pinta",
						"Aquilino Ribeiro", "Hipermercado",
						"P. Abílio Sampaio", "Junta Freg. Barca", "Gestalinho",
						"Barca" });

		STOPS_STCP.put("601", new String[] { "Cordoaria", "Carmo",
				"Hosp. Sto. António", "Palácio", "Pr. Da Galiza",
				"Boavista - B. Sucesso", "Boavista-Casa Da Música", "Graciosa",
				"Casa De Saúde Da Boavista", "Sidónio Pais",
				"Francos Z. Industr", "Rot. AEP", "Continente", "Hipódromo",
				"Q.ta Da Conceicão", "Assoc. Emp. Portugal", "Exponor",
				"Exponor", "Rot. Da Exponor", "Amorosa", "Bataria",
				"Almeiriga", "Monte Espinho", "Abade Mondego",
				"Joaquim Alves Da Silva", "Nó Freixieiro", "31 De Janeiro",
				"Oliveiras", "Farrapas", "Freixieiro (e.n.107)", "Telheira",
				"Barreiro", "Pedras Rubras", "Aeroporto" });

		STOPS_STCP.put("602", new String[] { "Cordoaria", "Carmo",
				"Hosp. Sto. António", "Maternidade", "Torrinha", "Carvalhosa",
				"Carolina Michaelis", "Cruz Vermelha", "Quinta Amarela",
				"Av. França", "Carvalhido", "Cintura Interna",
				"Parque Da Prelada", "Sra. Do Porto", "Monte Dos Burgos",
				"C. Seixo (sul)", "Fogueteiros (sul)", "C. Seixo (norte)",
				"Padrão Da Légua", "Vilarinho Freires", "Frei Álvaro Pinto",
				"Recarei (sul)", "Recarei Baixo", "Recarei (norte)",
				"Gondivai (sul)", "B. V. Leça Balio", "Gondivai (norte)",
				"R. Estação Araújo", "Araújo", "Pontelhas", "Custió", "Manso",
				"Monte Grande", "Sta. Luzia", "Ponte De Moreira", "Rio Leça",
				"Quinta De Moreira", "Real", "Padrão Moreira",
				"Gonçalo Mendes Maia", "C.c. Vivacci", "Guardeiras",
				"Cruz. Guardeiras", "R.5", "R.7(nascente)", "Rua 15", "Rua 1",
				"Rua 10", "R.7(poente)", "Cedro", "Pedras Rubras (estação)",
				"Dr. A. Carlos Maia", "Feira", "Pedras Rubras", "Aeroporto" });

		STOPS_STCP.put("603", new String[] { "Marquês", "Constituição",
				"Covelo", "Igreja De Paranhos", "Almeida Valente",
				"Almeida Valente", "ISEP", "Ilha Brava", "S. Tomé",
				"IPO (circunval.)", "Hosp. S. João (urgência)",
				"Ricardo Alves", "Feliciana", "Arroteia", "Sacadura Cabral",
				"J. Freguesia Pedrouços", "Pedrouços-bombeiros",
				"Pedrouços (cemitério)", "Cutamas", "Teibas", "Boi Morto",
				"Castro Meireles", "Paço", "Parada", "Terramonte",
				"Rod. Gonçalves Lage", "1º De Maio", "Agra", "Rot. Agra",
				"Matadouro", "Flores", "Gueifães", "Padre Américo",
				"M. Ferreira Pinto", "Penedos", "Enxinhães", "Largo Dos Mogos",
				"Casal Dos Mogos", "Cavaco", "Ponte Cabras", "Real",
				"Sto. Condestável", "Maninhos", "Macau", "Os Jacintos",
				"Quinta Nova", "D. Manuel II", "Souto", "Outeiro",
				"Tamanqueiros", "Vermoim", "Antunes Azevedo",
				"Padre Luis Campos", "António Marques", "Altos",
				"Maia (estádio)", "Sobreiro", "Maia", "Visconde Barreiros",
				"Jardim Zoológico", "Maia (zoo)" });

		STOPS_STCP.put("604", new String[] { "Hosp. S. João (metro)",
				"Ricardo Alves", "Feliciana", "Cavadas", "Iscap", "Dr. Barros",
				"Oliveira Gaio", "Moalde", "S. Mamede", "Santos Dias",
				"Laranjeiras", "Abel Salazar", "Zona Industrial",
				"Cemitério Novo", "Azenha Nova", "Malmequeres", "Mouta",
				"Arco", "Gueifães (esc.eb2/3)", "Flores", "Gueifães",
				"Padre Américo", "Sá E Melo", "Henrique Barros",
				"5 De Outubro", "Rot.lavrador", "Santos Leite",
				"Igreja Da Maia", "Lage", "Luis Camőes", "Sobreiro", "Maia",
				"Visconde Barreiros", "Jardim Zoológico", "Maia (zoo)",
				"Quinta Andorinhas", "Cons.costa Aroso", "Godim", "Guarda",
				"Châncidro", "Primavera", "Padrão Moreira", "Real",
				"Av.aeroporto", "Crestins (sta. Luzia)", "Sendal",
				"Crestins (metro)", "Rua Da Estrada", "Zona Industrial",
				"Barreiro", "Pedras Rubras", "Aeroporto" });

		STOPS_STCP.put("701", new String[] { "Bolhão", "Gonçalo Cristóvão",
				"Fontinha", "Doze Casas", "Marquês", "Perpétuo Socorro",
				"Combatentes", "Pires De Lima", "Silva Tapada",
				"Luis Woodhouse", "Conde Ferreira", "Barrocas", "Sta. Justa",
				"António Coelho", "Alto Da Areosa", "Areosa",
				"Areosa (mercado)", "Areosa (feira)", "Triana", "Giesta",
				"Crespo", "Forno", "Brás Oleiro", "Corim", "Coriscos", "Pícua",
				"Alto Da Maia", "Júlio Dinis", "Consolata",
				"Caloust Gulbenkian", "Saibreiras", "Porto Carreiro",
				"Cruzeiro", "Ermesinde (forum)", "Ermesinde - B. V.",
				"5 De Outubro", "Fonte", "Soutinho", "Ermida", "Reguengo",
				"Sra. Da Paz", "Cabeda", "Viela S. Vicente", "Oliveiras",
				"Aldeia Nova", "Barreira", "Igreja De Alfena", "Tv. Da Costa",
				"Alfena", "Alex. Herculano", "Lgo Da Codiceira",
				"Vasco Da Gama", "Codiceira" });

		STOPS_STCP.put("702", new String[] { "Bolhão", "Gonçalo Cristóvão",
				"Fontinha", "Doze Casas", "Marquês", "Perpétuo Socorro",
				"Combatentes", "Pires De Lima", "Silva Tapada",
				"Luis Woodhouse", "Conde Ferreira", "Barrocas", "Sta. Justa",
				"António Coelho", "Alto Da Areosa", "Areosa",
				"Areosa (mercado)", "Areosa (feira)", "Triana", "Giesta",
				"Crespo", "Forno", "Brás Oleiro", "Corim", "Coriscos", "Pícua",
				"Alto Da Maia", "Júlio Dinis", "Meilão", "Mirante", "Gandra",
				"Camélias", "Maiashopping", "Rodrigues Freitas", "Rio Leça",
				"Simőes Lopes", "Travagem" });

		STOPS_STCP.put("703", new String[] { "Cordoaria", "Av. Aliados",
				"Trindade", "João Regras", "Paraíso (metro)",
				"Hosp. Sta. Maria", "Marquês", "Marquês", "Perpétuo Socorro",
				"Combatentes", "Pires De Lima", "Silva Tapada",
				"Luis Woodhouse", "Conde Ferreira", "Barrocas", "Sta. Justa",
				"António Coelho", "Alto Da Areosa", "Areosa",
				"Areosa (mercado)", "Areosa (feira)", "Triana", "Giesta",
				"Crespo", "Forno", "Brás Oleiro", "Corim", "Coriscos", "Pícua",
				"Alto Da Maia", "Júlio Dinis", "Consolata",
				"Caloust Gulbenkian", "Saibreiras", "Porto Carreiro",
				"Cruzeiro", "Ermesinde (forum)", "Ermesinde - B. V.",
				"5 De Outubro", "Pinheiro", "Sonhos" });

		STOPS_STCP.put("704", new String[] { "Boavista - B. Sucesso",
				"Boavista-Casa Da Música", "Graciosa", "Carvalhido",
				"Br. Carvalhido", "Monsanto", "R. Particular Monsanto",
				"Arca D Água", "Cintura Interna", "Carlos Amarante",
				"Telheira", "Berlengas", "Amial", "S. Tomé",
				"IPO (circunval.)", "Hosp. S. João (circunvalação)", "Asprela",
				"Enxurreiras", "Areosa (mercado)", "Areosa (feira)", "Triana",
				"Giesta", "Crespo", "Forno", "Brás Oleiro", "Corim",
				"Coriscos", "Pícua", "Alto Da Maia", "Av. Lidador Da Maia",
				"Palmilheira", "Pavilhão Cpn", "João De Deus", "Cruzeiro",
				"Ermesinde (forum)", "Ermesinde - B. V.", "5 De Outubro",
				"R. Nova Da Fonte", "Marginal", "C. Saúde De Ermesinde",
				"Bela", "Boavista", "Vilar", "Monforte", "Passarias",
				"R. Funda", "D. Afonso Henriques", "Fonte", "Alfena",
				"Alex. Herculano", "Lgo Da Codiceira" });

		STOPS_STCP.put("705", new String[] { "Hosp. S. João (metro)",
				"Ricardo Alves", "Feliciana", "Cavadas", "Iscap", "Dr. Barros",
				"Oliveira Gaio", "Moalde", "S. Mamede", "Laranjeiras",
				"Tv. Henrique Bravo", "Leonardo Coimbra", "Parada",
				"Rod. Gonçalves Lage (este)", "Gago Coutinho", "Formigueiro",
				"António Santos", "R. Do Mosteiro", "Águas Santas", "Corga",
				"Lavadouros", "Júlio Dinis", "Meilão", "Mirante", "Gandra",
				"Camélias", "Maiashopping", "R. Igreja", "Ermesinde (igreja)",
				"Ermesinde (estação)", "Ermesinde (forum)", "Vasco Da Gama",
				"Ribeiro Teles", "Formiga Cemitério", "Chãos",
				"Montes Da Costa", "9 De Agosto", "Covina", "Fundição",
				"4 Caminhos", "Tapada Azevedo", "Flor Da Serra",
				"Alto Da Serra", "Ribeiro Cambado", "Fonte Da Senhora",
				"Conde Ferreira", "25 De Abril", "Pav. Gimnodesport.",
				"Calvário", "Câmara De Valongo", "Valongo (centro)", "Padrão",
				"Presa", "Aguiar Nogueira", "Valongo (estação)", "Queimada",
				"Fonte Mourisca", "Valongo" });

		STOPS_STCP.put("706", new String[] { "Hosp. S. João (metro)",
				"Asprela", "Enxurreiras", "Areosa (mercado)", "Areosa (feira)",
				"Humberto Delgado", "Tv. Nova Da Giesta", "Pedro Ivo",
				"Gil Vicente", "S. Gemil (caminho Ferro)", "D. Dinis",
				"5 De Outubro", "Dr. Carlos Felgueiras", "Sra. Da Guadalupe",
				"Formigueiro", "Gago Coutinho", "Rod. Gonçalves Lage (este)",
				"Parada", "Terramonte", "Rod. Gonçalves Lage", "1º De Maio",
				"Agra", "Vessada", "Arroteia", "R.conchas", "Aldeia Nova",
				"Zona Industrial", "Monte Penedo", "Primavera", "Pinhal",
				"Tv. De Ardegães", "Ardegães", "Pedro Hispano", "Sampaio",
				"Tv. Simões Lopes", "Travagem", "Rio Leça",
				"Rodrigues Freitas", "R. Igreja", "Ermesinde (igreja)",
				"Ermesinde (estação)" });

		STOPS_STCP.put("707", new String[] { "Hosp. S. João (metro)",
				"Asprela", "Enxurreiras", "Areosa (mercado)", "Areosa (feira)",
				"Humberto Delgado", "Tv. Nova Da Giesta", "Pedro Ivo",
				"Gil Vicente", "S. Gemil (caminho Ferro)", "D.dinis",
				"5 De Outubro", "Dr.carlos Felgueiras", "Sra. Da Guadalupe",
				"Formigueiro", "Gago Coutinho", "Rod. Gonçalves Lage (este)",
				"Parada", "Terramonte", "Rod. Gonçalves Lage", "1º De Maio",
				"Agra", "Vessada", "Arroteia", "R.conchas", "Aldeia Nova",
				"Arregadas", "Quelhas", "Arregadas (viaduto)", "Pisão",
				"R. Cristal", "Ardegães", "Pedro Hispano", "Sampaio",
				"Tv. Simőes Lopes", "Travagem", "Rio Leça",
				"Rodrigues Freitas", "R. Igreja", "Ermesinde (igreja)",
				"Ermesinde (estação)" });

		STOPS_STCP.put("800", new String[] { "Bolhão - Mercado",
				"Sta. Catarina", "Largo Do Padrão", "Campo 24 De Agosto",
				"Bonfim", "Godim", "Pr. Das Flores", "Av. 25 De Abril",
				"Fonte Velha", "Estádio Do Dragão", "Corujeira",
				"Ferr. Dos Santos", "Falcão", "Cartes", "Escolas", "S. Roque",
				"Tv. Da Ponte", "S. Caetano", "Soutelo Baixo", "Outeirinho",
				"Infante Santo", "Alto De Soutelo", "Dr. Américo Costa",
				"Carvalha", "Carvalha De Baixo", "Várzea", "Sta. Ovaia",
				"Sta. Cruz", "Sta. Eulália", "Capitão Moura", "Vilar",
				"Taralhão", "Vinhal", "Igreja Capuchinhos", "25 De Abril",
				"Combatentes G.guerra", "Gondomar (câmara)", "B. V. Gondomar",
				"Monte Crasto", "Gondomar (souto)" });

		STOPS_STCP.put("801", new String[] { "Cordoaria", "Pr. D. João I",
				"Sta. Catarina", "Largo Do Padrão", "Campo 24 De Agosto",
				"Bonfim", "Godim", "Pr. Das Flores", "Av. 25 De Abril",
				"Fonte Velha", "Estádio Do Dragão", "Corujeira",
				"Ferr. Dos Santos", "Falcão", "Cartes", "Escolas", "S. Roque",
				"Tv. Da Ponte", "S. Caetano", "Soutelo Baixo", "Outeirinho",
				"Infante Santo", "Alto De Soutelo", "Dr. Américo Costa",
				"Carvalha", "Carvalha De Baixo", "Várzea", "Sta. Ovaia",
				"Sta. Cruz", "Sta. Eulália", "Estivada", "Barreiros",
				"Alto Da Serra", "Bela Vista", "Curva Do 30", "Belo Horizonte",
				"Covilhã", "Rio Ferreira", "S. Pedro Da Cova" });

		STOPS_STCP.put("803", new String[] { "Boavista-B. Sucesso",
				"Boavista-Casa Da Música", "Graciosa", "Carvalhido", "Natária",
				"Bica Velha", "Silva Porto", "Vale Formoso", "Campo Lindo",
				"Lgo. Campo Lindo", "Univ. F. Pessoa", "Igreja De Paranhos",
				"Almeida Valente", "Almeida Valente", "Agra - Isep",
				"U.c.-biotecnologia", "Pólo Universitário (metro)",
				"Faculdade De Economia", "Faculdade De Engenharia",
				"Esc. Sup. Educação", "Asprela", "Enxurreiras", "Areosa",
				"Varziela", "Rebordãos", "Estrada Nova", "Castanheira",
				"Sistelo", "Bazar", "Rio Tinto (estação)",
				"Rio Tinto (estação)", "Perlinhas", "Lourinha", "Piscinas",
				"C. Saúde Rio Tinto", "David Correia Da Silva",
				"Sr.do Calvário", "Chão Verde", "Cavada Nova", "S. Sebastião",
				"Esc. Sec. De Rio Tinto", "Venda Nova" });

		STOPS_STCP.put("804", new String[] { "Hosp. S. João (circunvalação)",
				"Asprela", "Enxurreiras", "Areosa", "Varziela", "Rebordãos",
				"Ranha", "Parque Nascente", "Vila Cova", "Fábrica Do Cobre",
				"S. Roque G. Barros", "S. Roque", "Tv. Da Ponte", "S. Caetano",
				"Sr. Do Calvário", "Chão Verde", "Henrique Machado",
				"C.social Soutelo", "Urb. Soutelo", "Fânzeres (metro)",
				"Cabanas", "Carvalha De Baixo", "Várzea", "Sta. Ovaia",
				"Sta. Cruz", "Sta. Eulália", "Estivada", "Barreiros",
				"Alto Da Serra", "Bela Vista", "Curva Do 30", "Belo Horizonte",
				"Covilhã", "Rio Ferreira", "S. Pedro Da Cova", "Passal",
				"S.pedro C. /passal" });

		STOPS_STCP.put("805", new String[] { "Marquês", "R. Da Alegria",
				"Coutinho Azevedo", "S. Crispim", "Monte Aventino",
				"Antas (L. Cidadão)", "R. Contumil", "Br. Costa Cabral",
				"Sta. Justa", "Rodrigues Semide", "Rot. Da Areosa", "Areosa",
				"Enxurreiras", "J. Freguesia Pedrouços", "Luís De Camőes",
				"Humberto Delgado", "Tv. Nova Da Giesta", "Pedro Ivo",
				"Gil Vicente", "Forno", "Tv. Brás Oleiro", "Tv. Forno",
				"Carreiros", "João Pinto Ribeiro", "Santegãos",
				"Forças Armadas", "Padre Ivo Tonelli", "Casais Novos",
				"Medancelhe", "Dr. Porfírio Andrade", "Rio Tinto (estação)" });

		STOPS_STCP.put("806", new String[] { "Marquês", "R. Da Alegria",
				"Coutinho Azevedo", "S. Crispim", "Monte Aventino",
				"Alameda Das Antas", "Dolce Vita", "Estádio Do Dragão",
				"Corujeira", "Ferr. Dos Santos", "Falcão", "Cartes", "Escolas",
				"S. Roque", "Tv. Da Ponte", "Tv. Meiral", "António Aug. Silva",
				"Vitorino Nemesio", "Miradouro", "Praceta Areias",
				"Padre Dehon", "Tv. Cruzes", "Portelinha", "Oliveira Lobo",
				"Alto De Soutelo", "Dr. Américo Costa", "Carvalha",
				"Av. Carvalha" });

		STOPS_STCP.put("900", new String[] { "Trindade", "Av. Aliados",
				"Est. S. Bento", "Mouzinho Silveira", "Merc. Ferr. Borges",
				"Ribeira", "Elevador Guindais", "Ponte Luíz I",
				"Caves Vinho Porto", "GNR", "Sta. Marinha",
				"Lgo. Dos Aviadores", "Barrosa",
				"Tv. Conselheiro Veloso Da Cruz", "Alféres Pereira",
				"Visconde Devesas", "Soares Dos Reis", "D. Pedro V",
				"Parque Da República", "Mocambique", "D. João II (metro)",
				"Sto. Ovídio" });

		STOPS_STCP.put("901", new String[] { "Trindade", "Av. Aliados",
				"Est. S. Bento", "Mouzinho Silveira", "Merc. Ferr. Borges",
				"Ribeira", "Elevador Guindais", "Ponte Luíz I",
				"Caves Vinho Porto", "Mercado", "Lgo. Aljubarrota",
				"Lgo. Cruz", "Fonte Nova", "Viterbo Campos", "Agro",
				"Alam. Empresa", "Lgo. Montinho", "Lgo. Eça Queirós",
				"Tv. Fonte Lodosa", "Major Pála", "Pr. M. Silva Reis",
				"Lavouras", "Coimbrőes", "Augusto Gomes", "R. Das Matas",
				"Quinta Bela Vista", "Gandara", "Pitada", "Rego D Água",
				"Nova Lisboa", "Praceta Oliveiras", "Maninho", "Gomes Júnior",
				"Aguim", "Isolino Sousa", "Cabine", "Sto. António",
				"Sousa Nogueira", "Crasto", "Alberto O Cantador",
				"José Portugal", "Campolinho", "Estr. Nacional 109",
				"Valadares", "Largo Eirós", "Tv. Penedo", "Seminário",
				"Valadares (escolas)" });

		STOPS_STCP.put("902", new String[] { "Casa Da Música (metro)",
				"Boavista-Casa Da Música", "Bom Sucesso", "Pr. Da Galiza",
				"Junta Massarelos", "Gólgota", "Chãs", "Nó Candal",
				"Arrábidashopping", "Camilo C. Branco", "28 De Janeiro",
				"Electrocerâmica", "Lgo. Montinho", "Lgo. Eça Queirós",
				"Tv. Fonte Lodosa", "R. Fonte Lodosa", "R. Tenente Valadim",
				"Quatro Caminhos", "Espinheiro", "Sport Clube Canidelo",
				"Braga Júnior", "Cancelinhas", "Alumiara", "Fontes", "Picão",
				"Areias Cabedelo", "Estamparia Lavadores", "Jorge Dias",
				"Lavadores (praia)" });

		STOPS_STCP.put("903", new String[] { "Casa Da Música (metro)",
				"Boavista-Casa Da Música", "Bom Sucesso", "Pr. Da Galiza",
				"Junta Massarelos", "Gólgota", "Chãs", "Jardins Da Arrábida",
				"Arrábidashopping", "Camilo C. Branco", "28 De Janeiro",
				"Electrocerâmica", "Lgo. Montinho", "Lgo. Eça Queirós",
				"Tv. Fonte Lodosa", "Major Pála", "Pr. M. Silva Reis",
				"Lavouras", "Coimbrőes 1", "Regueira", "Arco Do Prado",
				"Rio Da Fonte", "Henrique Cernache", "Aki", "Makro",
				"Gaiashopping", "Telheira", "Infante D. Henrique",
				"Soares Dos Reis", "D. Pedro V", "Parque Da República",
				"Mocambique", "D. João II (metro)", "Sto. Ovídio",
				"António R. Rocha", "Fernão Mendes Pinto", "Gomes Azurara",
				"Bernardim Ribeiro", "Br. Cedro", "Alam. Cedro", "Laborim" });

		STOPS_STCP.put("904", new String[] { "Trindade", "Av. Aliados",
				"Est. S. Bento", "Lgo. 1º Dezembro", "Batalha",
				"Escarpa Serra Pilar", "Quartel Srr. Pilar", "Jardim Do Morro",
				"General Torres", "Tribunal De Gaia", "Dispensário",
				"Devesas (estação)", "Mariani", "Arco Do Prado",
				"Cemitério Sta. Marinha", "B. V. Coimbrőes", "Lavouras",
				"Coimbrőes", "Augusto Gomes", "R. Das Matas",
				"Quinta Bela Vista" });

		STOPS_STCP.put("905", new String[] { "Bolhão", "Mercado Do Bolhão",
				"Pr. D. João I", "Av. Aliados", "Est. S. Bento",
				"Lgo. 1º Dezembro", "Batalha", "Escarpa Serra Pilar",
				"Quartel Srr. Pilar", "Jardim Do Morro", "General Torres",
				"Tribunal De Gaia", "Lgo. Dos Aviadores", "Barrosa",
				"Tv. Conselheiro Veloso Da Cruz", "Alféres Pereira",
				"Visconde Devesas", "Soares Dos Reis", "C. Saúde S. Reis",
				"L. Estevão Torres", "Sto. Ovídio", "Clube Caçadores",
				"Cravel", "RTP", "Esc. Eb 2/3 S Reis", "Sardoal", "Egas Moniz",
				"Hosp. Santos Silva", "Monte Da Virgem" });

		STOPS_STCP.put("906", new String[] { "Trindade", "Av. Aliados",
				"Est. S. Bento", "Mouzinho Silveira", "Merc. Ferr. Borges",
				"Ribeira", "Elevador Guindais", "Ponte Luíz I",
				"Caves Vinho Porto", "Mercado", "Lgo. Aljubarrota",
				"Lgo. Cruz", "Fonte Nova", "Viterbo Campos", "Agro",
				"Alam. Empresa", "Lgo. Montinho", "Lgo. Eça Queirós",
				"Tv. Fonte Lodosa", "Major Pála", "Pr. M. Silva Reis",
				"Lavouras", "Coimbrőes", "Augusto Gomes", "R. Das Matas",
				"Quinta Bela Vista", "Gandara", "Pitada", "Rego D Água",
				"Nova Lisboa", "Praceta Oliveiras", "Maninho", "Gomes Júnior",
				"Aguim", "Isolino Sousa", "Cabine", "José Poças", "Monte",
				"Tv. Loureiro", "Tv. Aldeia Nova", "Carvalheiro",
				"Aldeia Nova", "Nazarães", "R. Marinha", "Praia Madalena Sul",
				"Moinho Vento", "Cerro", "Parque Campismo", "R. Chaquedas",
				"Alto Chaquedas", "R. Zambueiras", "R. Rodelo",
				"Madalena (escolas)", "Madalena" });

		STOPS_STCP.put("907", new String[] { "Boavista (bom Sucesso)",
				"Gonçalo Sampaio", "Gólgota", "Chãs", "Nó Candal",
				"Arrábidashopping", "Camilo C. Branco", "28 De Janeiro",
				"Electrocerâmica", "Lgo. Montinho", "Lgo. Eça Queirós",
				"Tv. Fonte Lodosa", "Major Pála", "Pr. M. Silva Reis",
				"Lavouras", "Coimbrőes", "Augusto Gomes", "R. Das Matas",
				"Tv. Matas", "R. Sr Matosinhos", "Makro", "Gaiashopping",
				"Telheira", "Infante D. Henrique", "Soares Dos Reis",
				"C. Saúde S. Reis", "L. Estevão Torres", "Sto. Ovídio",
				"Clube Caçadores", "Rosário", "RTP", "Esc. Eb 2/3 S Reis",
				"Sardoal", "Egas Moniz", "Hosp. Santos Silva",
				"Monte Da Virgem", "Salgueiro Maia", "Mimosas",
				"Urb. Vila D Este", "Vila D Este (escolas)", "Vila D Este" });

		STOPS_STCP.put("ZF", new String[] { "Valadares (est)", "Campolinho",
				"José Portugal", "Cedofeita", "Bicheiros", "Bela", "Roçadas",
				"Pereira Melo", "Nuno Tristão", "Infante Santo", "Vasco Gama",
				"Álvares Cabral", "Infante Sagres", "Francelos-praia",
				"Francelos" });

		STOPS_STCP.put("ZL", new String[] { "Casa Da Música (metro)",
				"Boavista-Casa Da Música", "Boavista Cemitério", "Bom Sucesso",
				"Pr. Da Galiza", "Junta Massarelos", "Planetário",
				"Feliciano Castilho", "António Patrício", "Bairro Bessa Leite",
				"Lordelo", "Mouteira", "Pintor Arpad Szenes", "Mascarenhas",
				"Pasteleira", "Palmeiras", "Aleixo", "Mocidade Arrábida",
				"Largo Pinto Correia", "Tv. Entre Campos",
				"Faculdade Arquitectura", "Planetário", "Junta Massarelos",
				"Pr. Da Galiza", "Boavista - B. Sucesso",
				"Boavista-Casa Da Música", "Casa Da Música (metro)" });

		STOPS_STCP.put("ZM", new String[] { "Cordoaria", "R. Caldeireiros",
				"Loios", "R. Flores", "S. Domingos", "Ribeira (infante)",
				"Miragaia", "Alfândega", "Museu Vinho Porto",
				"Museu C. Eléctrico", "Salgueiro Maia", "D. Pedro V",
				"R. Campo Alegre", "Bom Sucesso" });

		STOPS_STCP.put("ZR", new String[] { "Alfândega", "Miragaia",
				"Ribeira (infante)", "Ribeira", "Elevador Guindais",
				"Guindais", "Alameda", "Pte. D. Maria Pia", "Fornos",
				"Varandas", "J.a.e.", "Areinho", "Freixo", "Sra. Da Hora",
				"S. Pedro", "Meiral", "Viela Meiral", "Lagarteiro", "Azevedo",
				"Tv. Aldeia", "Pêgo Negro", "João De Deus", "Areias" });

		STOPS_STCP.put("1M", new String[] { "Av. Aliados", "Est. S. Bento",
				"Mouzinho Silveira", "Merc. Ferr. Borges", "Ribeira (infante)",
				"Miragaia", "Alfândega", "Museu Vinho Porto",
				"Museu C. Eléctrico", "Salgueiro Maia", "D. Pedro V",
				"Junta Massarelos", "Planetário", "Casa Das Artes",
				"Jardim Botânico", "Lordelo", "Palmeiras", "Fluvial (norte)",
				"Paulo Da Gama", "Pasteleira", "Torres", "Padre Luis Cabral",
				"Univ. Católica", "Pr. Do Império", "Mercado Da Foz",
				"Praia Da Luz", "Praia De Gondarém", "Crasto", "Molhe",
				"Homem Do Leme", "Pêro Da Covilhã", "Timor",
				"Castelo Do Queijo", "Edif. Transparente", "Pr. Cid. Salvador",
				"Sousa Aroso", "D. João I", "Comendador Ferreira Matos",
				"Fonte Luminosa" });

		STOPS_STCP.put("3M", new String[] { "Av. Aliados", "Trindade",
				"Gonçalo Cristóvão", "Pr. Da República", "Figueiroa",
				"Carvalhosa", "Carolina Michaelis", "Cruz Vermelha",
				"Quinta Amarela", "Av.frança", "Carvalhido", "Cintura Interna",
				"Parque Da Prelada", "Sra. Do Porto", "Monte Dos Burgos",
				"C. Seixo (sul)", "Fogueteiros (sul)", "C. Seixo (norte)",
				"Padrão Da Légua", "Vilarinho Freires", "Frei Álvaro Pinto",
				"Recarei (sul)", "Recarei Baixo", "Recarei (norte)",
				"Gondivai (sul)", "B. V. Leça Balio", "Gondivai (norte)",
				"R. Estação Araújo", "Araújo", "Pontelhas", "Custió", "Manso",
				"Monte Grande", "Sta.luzia", "Ponte De Moreira", "Rio Leça",
				"Crestins (Sta. Luzia)", "Sendal", "Crestins (metro)",
				"Rua Da Estrada", "Zona Industrial", "Barreiro",
				"Pedras Rubras", "Aeroporto" });

		STOPS_STCP.put("4M", new String[] { "Av. Aliados", "Trindade",
				"Gonçalo Cristóvão", "Pr. Da República", "Lapa",
				"Hosp. Sta. Maria", "Constituição", "Vale Formoso",
				"C. Saúde Paranhos", "Arca D Água", "Cintura Interna",
				"Carlos Amarante", "Telheira", "Berlengas", "Amial",
				"Telheiro", "Flores", "S. Mamede (mercado)", "S. Mamede",
				"Sá E Melo", "C. Saúde S. Mamede", "Abel Salazar",
				"Ponte Da Pedra", "Pedro Mesquita", "Camilo C. Branco",
				"Santana", "Sra. Da Saúde", "Antonio Aleixo", "Catassol",
				"Combonianos", "Rot. Lavrador", "Santos Leite",
				"Igreja Da Maia", "Maia (câmara)", "Maia" });

		STOPS_STCP.put("5M", new String[] { "Av. Aliados", "Sá Bandeira",
				"Bolhão (firmeza)", "Gonçalo Cristóvão", "Fontinha",
				"Doze Casas", "Marquês", "Perpétuo Socorro", "Combatentes",
				"Pires De Lima", "Silva Tapada", "Luis Woodhouse",
				"Conde Ferreira", "Barrocas", "Sta. Justa", "António Coelho",
				"Alto Da Areosa", "Areosa", "Areosa (mercado)areosa (feira)",
				"Triana", "Giesta", "Crespo", "Forno", "Brás Oleiro", "Corim",
				"Coriscos", "Pícua", "Alto Da Maia", "Júlio Dinis", "Meilão",
				"Mirante", "Gandra", "Camélias", "Maiashopping",
				"Ermesinde (igreja)", "Ermesinde (estação)" });

		STOPS_STCP.put("7M", new String[] { "Av. Aliados", "Sá Da Bandeira",
				"Sta. Catarina", "Largo Do Padrão", "Campo 24 De Agosto",
				"Bonfim", "Godim", "Pr. Das Flores", "Av. 25 De Abril",
				"Fonte Velha", "Estádio Do Dragão", "Corujeira",
				"Ferr. Dos Santos", "Falcão", "Cartes", "Escolas", "S. Roque",
				"Tv. Da Ponte", "S. Caetano", "Sr. Do Calvário", "Chão Verde",
				"Cavada Nova", "S. Sebastião", "Venda Nova", "Ferraria",
				"Carreira", "Pontelhas", "Vale Ferreiros", "Entre Cancelas",
				"Regadas", "Seixo", "Agostinho A. Sousa", "Monte Pedro",
				"Estr. D. Miguel", "Alto Da Serra", "Ribeiro Cambado",
				"Fonte Da Senhora", "Conde Ferreira", "25 De Abril",
				"Pav. Gimnodesport.", "Calvário", "Câmara De Valongo",
				"Valongo (centro)" });

		STOPS_STCP.put("8M", new String[] { "Av. Aliados", "Sá Da Bandeira",
				"Sta. Catarina", "Largo Do Padrão", "Campo 24 De Agosto",
				"Nave", "Barros Lima", "Esc. Soares Dos Reis", "S. Crispim",
				"Monte Aventino", "Antas (L. Cidadão)", "R. Contumil",
				"Br. Costa Cabral", "Sta. Justa", "Rodrigues Semide",
				"Rot. Da Areosa", "Varziela", "Rebordãos", "Estrada Nova",
				"Castanheira", "Levada", "Igreja Rio Tinto", "Chão Verde",
				"Henrique Machado", "C. Social Soutelo", "Urb. Soutelo",
				"Fânzeres (metro)", "Cabanas", "Carvalha De Baixo", "Várzea",
				"Sta. Ovaia", "Sta. Cruz", "Sta. Eulália", "Estivada",
				"Barreiros", "Alto Da Serra", "Bela Vista", "Curva Do 30",
				"Belo Horizonte", "Covilhã" });

		STOPS_STCP.put("9M", new String[] { "Rot. AEP", "Ruela", "Sra. Penha",
				"Bairro Do Viso", "R. Do Senhor", "Alto Do Viso",
				"Quartel Militar", "Br. Sto. Eugénio", "Congostas",
				"Mte Burgos (circ.)", "Via Norte (circ.)", "Capuchinhos",
				"Amial", "S. Tomé", "IPO (circunval.)",
				"Hosp. S. João (circunvalação)", "Asprela", "Enxurreiras",
				"Areosa", "Varziela", "Rebordãos", "Ranha", "Parque Nascente",
				"Vila Cova", "Fábrica Do Cobre", "S. Roque G. Barros",
				"S. Roque", "Tv. Da Ponte", "S. Caetano", "Soutelo Baixo",
				"Outeirinho", "Infante Santo", "Alto De Soutelo",
				"Dr. Américo Costa", "Carvalha", "Carvalha De Baixo", "Várzea",
				"Sta. Ovaia", "Sta. Cruz", "Sta. Eulália", "Capitão Moura",
				"Vilar", "Taralhão", "Vinhal", "Igreja Capuchinhos",
				"25 De Abril", "Combatentes G. Guerra", "Gondomar (câmara)",
				"B. V. Gondomar", "Monte Crasto", "Gondomar (souto)" });

		STOPS_STCP.put("10M", new String[] { "Av. Aliados", "Trindade",
				"Av. Aliados", "Est. S. Bento", "Mouzinho Silveira",
				"Merc. Ferr. Borges", "Ribeira", "Elevador Guindais",
				"Ponte Luíz I", "Caves Vinho Porto", "Mercado",
				"Lgo. Aljubarrota", "Serpa Pinto",
				"Conselheiro Veloso Da Cruz", "Dispensário",
				"Tribunal De Gaia", "Lgo. Dos Aviadores", "Barrosa",
				"Tv. Conselheiro Veloso Da Cruz", "Alféres Pereira",
				"Visconde Devesas", "Soares Dos Reis", "C. Saúde S. Reis",
				"L. Estevão Torres", "Sto. Ovídio", "Clube Caçadores",
				"Cravel", "RTP", "Esc. Eb 2/3 S Reis", "Sardoal", "Egas Moniz",
				"Hosp. Santos Silva", "Monte Da Virgem", "Salgueiro Maia",
				"Mimosas", "Urb. Vila D'este", "Vila D'este" });

		STOPS_STCP.put("11M", new String[] { "Hosp. S. João (urgência)",
				"Esc. Sup. Educação", "Faculdade De Engenharia",
				"Faculdade De Economia", "Cemitério Paranhos",
				"Igreja De Paranhos", "Covelo", "Constituição",
				"Hosp. Sta. Maria", "Paraíso (metro)", "Gonçalo Cristóvão",
				"Trindade", "Av. Aliados", "Est. S. Bento", "Lgo. 1º Dezembro",
				"Batalha", "Escarpa Serra Pilar", "Quartel Srr. Pilar",
				"Jardim Do Morro", "General Torres", "Câmara De Gaia",
				"Pádua Correia", "Lgo. Dos Aviadores", "Tribunal De Gaia",
				"Dispensário", "Devesas (estação)", "Mariani", "Arco Do Prado",
				"Cemitério Sta. Marinha", "B.v. Coimbrőes", "Lavouras",
				"Coimbrőes", "Augusto Gomes", "R. Das Matas",
				"Quinta Bela Vista" });

		STOPS_STCP.put("12M", new String[] { "Av. Aliados", "Trindade",
				"Av. Aliados", "Guil. G. Fernandes", "Carmo",
				"Hosp. Sto. António", "Palácio", "Pr. Da Galiza",
				"Junta Massarelos", "Gólgota", "Chãs", "Jardins Da Arrábida",
				"Arrábidashopping", "Camilo C. Branco", "28 De Janeiro",
				"Electrocerâmica", "Lgo. Montinho", "Lgo. Eça Queirós",
				"Tv. Fonte Lodosa", "Major Pála", "Pr. M. Silva Reis",
				"Lavouras", "Coimbrőes 1", "Regueira", "Arco Do Prado",
				"Rio Da Fonte", "Henrique Cernache", "Aki", "Makro",
				"Gaiashopping", "Telheira", "Infante D. Henrique",
				"Soares Dos Reis", "C. Saúde S. Reis", "L. Estevão Torres",
				"Sto. Ovídio" });

		STOPS_STCP.put("13M", new String[] { "Av. Aliados",
				"Guil. G. Fernandes", "Carmo", "Hosp. Sto. António", "Palácio",
				"Pr. Da Galiza", "Boavista - B. Sucesso",
				"Boavista-Casa Da Música", "Graciosa",
				"Casa De Saúde Da Boavista", "Sidónio Pais", "Rot. Do Bessa",
				"Francos (bombeiros)", "Casa De Ramalde", "C. Saúde Ramalde",
				"Br. Campinas", "Antunes Guimarães", "Pereiró",
				"Ezequiel Campos", "Man.p.azevedo 3", "Continente",
				"Azenha De Cima", "Hosp. P. Hispano", "Quinta Seca",
				"Parque De Real", "E. Sec. G. Zarco", "D. Nuno A. Pereira",
				"Carcavelos", "Matosinhos (CMM)", "Goa", "Pq Basílio Teles",
				"Godinho", "1º De Dezembro", "Matosinhos Mercado" });

		SERVICES.put("Metro do Porto", STOPS_MPORTO);
		SERVICES.put("STCP", STOPS_STCP);
	}

}